language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t xunyuanxin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xunyuanxin/react-test npm test

after_success:
  - docker build -t xunyuanxin/multi-client ./client
  - docker build -t xunyuanxin/multi-nginx ./nginx
  - docker build -t xunyuanxin/multi-server ./server
  - docker build -t xunyuanxin/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push xunyuanxin/multi-client
  - docker push xunyuanxin/multi-nginx
  - docker push xunyuanxin/multi-server
  - docker push xunyuanxin/multi-worker

deploy:
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-413208394742"
  bucket_path: "docker-multi"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY