language: generic
sudo: required
services:
  - docker

before_install:
  # 👇 Fix Nokogiri compatibility by forcing source build
  - sudo apt-get update && sudo apt-get install -y ruby-full
  - gem install bundler
  - bundle config set force_ruby_platform true

  - docker build -t xunyuanxin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xunyuanxin/react-test npm test

after_success:
  - docker build -t xunyuanxin/multi-client ./client
  - docker build -t xunyuanxin/multi-nginx ./nginx
  - docker build -t xunyuanxin/multi-server ./server
  - docker build -t xunyuanxin/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push xunyuanxin/multi-client
  - docker push xunyuanxin/multi-nginx
  - docker push xunyuanxin/multi-server
  - docker push xunyuanxin/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-413208394742
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY